workflow:
  rules:
  - if: '$CI_COMMIT_BRANCH == "feature/k8s"'
  - when: always

stages:
- build
- deploy

# ------------------------------
# BUILD STAGE
# ------------------------------
.build_and_push_template:
  stage: build
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - export IMAGE_NAME="$CI_REGISTRY_IMAGE/$SERVICE_NAME"
  - export IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
  script:
  - docker build -t $IMAGE_NAME:$IMAGE_TAG ./$SERVICE_NAME
  - docker push $IMAGE_NAME:$IMAGE_TAG

build_and_push_frontend:
  extends: .build_and_push_template
  variables:
    SERVICE_NAME: "client"
  rules:
  - changes:
    - "client/**/*"

build_and_push_backend:
  extends: .build_and_push_template
  variables:
    SERVICE_NAME: "server"
  rules:
  - changes:
    - "server/**/*"

# ------------------------------
# DEPLOY STAGE
# ------------------------------
.deploy_template:
  stage: deploy
  image: alpine/k8s:1.29.2
  before_script:
  - export KUBECONFIG="$KUBE_CONFIG"

  - export NAMESPACE="mern-recipe-app"
  - export CLIENT_IMAGE="$CI_REGISTRY_IMAGE/client"
  - export SERVER_IMAGE="$CI_REGISTRY_IMAGE/server"
  - export IMAGE_TAG="$CI_COMMIT_SHORT_SHA"

  - |
    kubectl create secret docker-registry regcred \
      --docker-server="$CI_REGISTRY" \
      --docker-username="$DEPLOY_TOKEN_USERNAME" \
      --docker-password="$DEPLOY_TOKEN_PASSWORD" \
      --namespace $NAMESPACE || echo "Secret regcred already exists"

deploy_frontend:
  extends: .deploy_template
  variables:
    SERVICE_NAME: "client"
  script:
  - echo "🚀 Deploying $SERVICE_NAME to Kubernetes namespace $NAMESPACE..."

  - sed -i "s|\${CLIENT_IMAGE}|$CLIENT_IMAGE|g" client/kubernetes/deployment.yml
  - sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" client/kubernetes/deployment.yml

  - kubectl apply -f client/kubernetes/deployment.yml -n $NAMESPACE
  - kubectl apply -f client/kubernetes/service.yml -n $NAMESPACE
  rules:
  - changes:
    - "client/**/*"

deploy_backend:
  extends: .deploy_template
  variables:
    SERVICE_NAME: "server"
  script:
  - echo "🚀 Deploying $SERVICE_NAME to Kubernetes namespace $NAMESPACE...

  - |
    kubectl create secret docker-registry regcred \
      --docker-server="$CI_REGISTRY" \
      --docker-username="$DEPLOY_TOKEN_USERNAME" \
      --docker-password="$DEPLOY_TOKEN_PASSWORD" \
      --namespace $NAMESPACE || echo "Secret regcred already exists"
  - |
    kubectl create secret generic backend-env \
      --from-literal=DATABASE="$DATABASE" \
      --from-literal=DATABASE_PASSWORD="$DATABASE_PASSWORD" \
      --from-literal=JWT_SECRET="$JWT_SECRET" \
      --from-literal=JWT_EXPIRES_IN="$JWT_EXPIRES_IN" \
      --from-literal=JWT_COOKIE_EXPIRES_IN="$JWT_COOKIE_EXPIRES_IN" \
      --from-literal=NODE_ENV="$NODE_ENV" \
      --from-literal=PORT="$PORT" \
      --namespace $NAMESPACE \
      --dry-run=client -o yaml | kubectl apply -f -

  - sed -i "s|\${SERVER_IMAGE}|$SERVER_IMAGE|g" server/kubernetes/deployment.yml
  - sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" server/kubernetes/deployment.yml

  - kubectl apply -f server/kubernetes/deployment.yml -n $NAMESPACE
  - kubectl apply -f server/kubernetes/service.yml -n $NAMESPACE
  rules:
  - changes:
    - "server/**/*"
