workflow:
  rules:
  - if: '$CI_COMMIT_BRANCH == "feature/deploy-to-k8s"'
    when: always

stages:
- build
- deploy

# ------------------------------
# BUILD STAGE
# ------------------------------
.build_and_push_template:
  stage: build
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - export IMAGE_NAME="$CI_REGISTRY_IMAGE/$SERVICE_NAME"
  - export IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
  script:
  - docker build -t $IMAGE_NAME:$IMAGE_TAG ./$SERVICE_NAME
  - docker push $IMAGE_NAME:$IMAGE_TAG

build_and_push_frontend:
  extends: .build_and_push_template
  variables:
    SERVICE_NAME: "client"
  rules:
  - changes:
    - "client/**/*"

build_and_push_backend:
  extends: .build_and_push_template
  variables:
    SERVICE_NAME: "server"
  rules:
  - changes:
    - "server/**/*"

# ------------------------------
# DEPLOY STAGE
# ------------------------------
.deploy_template:
  stage: deploy
  before_script:
  - chmod 400 $SSH_PRIVATE_KEY
  - export IMAGE_NAME="$CI_REGISTRY_IMAGE/$SERVICE_NAME"
  - export IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
  script:
  - echo "🚀 Deploying $SERVICE_NAME..."
  - scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY docker-compose.yml $SSH_USER@$SSH_HOST:~/
  - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $SSH_USER@$SSH_HOST " export IMAGE_NAME='$IMAGE_NAME' && export IMAGE_TAG='$IMAGE_TAG' && docker login -u '$CI_REGISTRY_USER' -p '$CI_REGISTRY_PASSWORD' '$CI_REGISTRY' && docker compose pull $SERVICE_NAME && docker compose up -d $SERVICE_NAME && docker system prune -af --volumes "
  - echo "✅ Deployment complete for $SERVICE_NAME"

deploy_frontend:
  extends: .deploy_template
  variables:
    SERVICE_NAME: "client"
  rules:
  - changes:
    - "client/**/*"

deploy_backend:
  extends: .deploy_template
  variables:
    SERVICE_NAME: "server"
  rules:
  - changes:
    - "server/**/*"
