services:
    client:
        image: "${IMAGE_NAME}:${IMAGE_TAG}"
        container_name: client
        ports:
            - "3000:80"
        depends_on:
            - server
        networks:
            - app-network
        restart: always

    server:
        image: "${IMAGE_NAME}:${IMAGE_TAG}"
        container_name: server
        networks:
            - app-network
        restart: always
        # Uncomment for debugging
        # ports:
        #   - "5000:5000"

networks:
    app-network:
        driver: bridge
