version: "3.9"

services:
    frontend:
        image: "${IMAGE_NAME}:${IMAGE_TAG}"
        container_name: frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - app-network
        restart: always

    backend:
        image: "${IMAGE_NAME}:${IMAGE_TAG}"
        container_name: backend
        networks:
            - app-network
        restart: always
        # Uncomment for debugging
        # ports:
        #   - "5000:5000"

networks:
    app-network:
        driver: bridge
