services:
    server:
        image: "${SERVER_IMAGE}:${IMAGE_TAG}"
        container_name: server
        networks:
            - app-network
        restart: always
        env_file:
            - ~/.env.server

networks:
    app-network:
        driver: bridge
        name: app-network
