services:
    client:
        image: "${CLIENT_IMAGE}:${IMAGE_TAG}"
        container_name: client
        ports:
            - "3000:80"
        networks:
            - app-network
        restart: always

networks:
    app-network:
        driver: bridge
        name: app-network
